### ISSUE TITLE
Suggestion: Change "name" to include $0

### ISSUE THREAD

**Issue by jhthorsen** [jhthorsen/mojo-irc#26]
I wonder if we should change the default "name" attribute to include the application name. Something like this:

    has name => sub {
      my $app = basename $0;
      return "Mojo-IRC/$app";
    };

**Comment by marcusramberg** [comment]
This change seems a little magic to me. I think it should probably be the responsibility of the app to decide what name to present.

**Comment by jhthorsen** [comment]
Thanks!
