### ISSUE TITLE
t/ua-mode.t fails

### ISSUE THREAD

**Issue by jberger** [jhthorsen/mojo-irc#28]
As seen on cpan testers and I can report locally, t/ua-mode.t fails on the two user mode test attempts (4 total test failures, 2 per test attempt). I spent some time trying to debug but I couldn't figure out what was wrong.

**Comment by jberger** [comment]
I can say for sure that the guard in Test::Mojo::IRC is firing its timeout.

**Comment by jhthorsen** [comment]
Yeah, this one is tricky (at least for me), since it does not fail _all_the_time_

**Comment by jberger** [comment]
It fails for me every time. Could it be a timing issue?

**Comment by jhthorsen** [comment]
Soon available on CPAN. Thanks for reminding me 👍

**Comment by jhthorsen** [comment]
It's still failing, even if I can't make it fail locally:

http://www.cpantesters.org/cpan/report/0521b3d4-7481-11e6-8452-fb0924312fb7

    while true; do prove -l t/ua-mode.t ; done

**Comment by jberger** [comment]
Honestly, give it a little bit too see if you get any more fails. In my
experience slaven's smokers do that sometimes. I suspect he downloads the
files as they are updated but reports them as they currently exist.
